###
 # THIS FILE IS AUTOMATICALLY GENERATED
 # Do not edit this file. It will be overwritten when the configure script is run.
###

######
# Build ID: aad0371488f95757
# Executable: ./bin/champsim
# Module Names: ('btbDbasic_btb', 'branchDbimodal', 'branchDgshare', 'branchDhashed_perceptron', 'branchDmybranch', 'branchDperceptron', 'branchDstatic_taken', 'branchDtage2', 'prefetcherDip_stride', 'prefetcherDnext_line', 'prefetcherDno', 'prefetcherDspp_dev', 'prefetcherDva_ampm_lite', 'replacementDdrrip', 'replacementDlru', 'replacementDrandom', 'replacementDship', 'replacementDsrrip')
######

BIN_ROOT := bin
$(BIN_ROOT)/champsim: build_id := aad0371488f95757
nonbase_module_objs += $(filter-out $(base_module_objs),$(call get_module_list, btb/basic_btb \
  branch/bimodal branch/gshare branch/hashed_perceptron \
  branch/mybranch branch/perceptron branch/static_taken \
  branch/tage2 prefetcher/ip_stride prefetcher/next_line \
  prefetcher/no prefetcher/spp_dev prefetcher/va_ampm_lite \
  replacement/drrip replacement/lru replacement/random \
  replacement/ship replacement/srrip ))
executable_name += $(BIN_ROOT)/champsim
